### ISSUE TITLE
Wordpress integration not working.

### ISSUE THREAD

**Issue by dorianborovina** [formbricks/wordpress#14]
Hello everyone,

I followed the steps to integrate the Formbricks to my Wordpress page.

Downloaded and installed the plugin, changed the EnvironmentID and the App URL to point to my self-hosted instance.

Connection test was successful and the UI is saying Receiving Data as well as "Website connected".  ✅ 

The website is not showing the survey even though everything seems to be working fine.

The trigger is set to "New Session", without delay, and Recontact Options are set to "Until they submit a response".

There are some Docker log erros and Browser console errors.

Any idea?

Thanks! 

![image](https://github.com/user-attachments/assets/23b8909b-90e2-480b-bc39-30a00ba2dc1a)

Here are console logs:

`formbricks-1  | Falling back to LRU handler because Redis client is not available.
formbricks-1  | d [ZodError]: [
formbricks-1  |   {
formbricks-1  |     "code": "invalid_union",
formbricks-1  |     "unionErrors": [
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "openText",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"openText\""
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "consent",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"consent\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "string",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "label"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "multipleChoiceSingle",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"multipleChoiceSingle\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "array",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "choices"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "multipleChoiceMulti",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"multipleChoiceMulti\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "array",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "choices"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "nps",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"nps\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "string",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "lowerLabel"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "string",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "upperLabel"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "cta",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"cta\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "boolean",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "buttonExternal"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "rating",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"rating\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "expected": "'number' | 'smiley' | 'star'",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "scale"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_union",
formbricks-1  |             "unionErrors": [
formbricks-1  |               {
formbricks-1  |                 "issues": [
formbricks-1  |                   {
formbricks-1  |                     "code": "invalid_literal",
formbricks-1  |                     "expected": 5,
formbricks-1  |                     "path": [
formbricks-1  |                       "questions",
formbricks-1  |                       6,
formbricks-1  |                       "range"
formbricks-1  |                     ],
formbricks-1  |                     "message": "Invalid literal value, expected 5"
formbricks-1  |                   }
formbricks-1  |                 ],
formbricks-1  |                 "name": "ZodError"
formbricks-1  |               },
formbricks-1  |               {
formbricks-1  |                 "issues": [
formbricks-1  |                   {
formbricks-1  |                     "code": "invalid_literal",
formbricks-1  |                     "expected": 3,
formbricks-1  |                     "path": [
formbricks-1  |                       "questions",
formbricks-1  |                       6,
formbricks-1  |                       "range"
formbricks-1  |                     ],
formbricks-1  |                     "message": "Invalid literal value, expected 3"
formbricks-1  |                   }
formbricks-1  |                 ],
formbricks-1  |                 "name": "ZodError"
formbricks-1  |               },
formbricks-1  |               {
formbricks-1  |                 "issues": [
formbricks-1  |                   {
formbricks-1  |                     "code": "invalid_literal",
formbricks-1  |                     "expected": 4,
formbricks-1  |                     "path": [
formbricks-1  |                       "questions",
formbricks-1  |                       6,
formbricks-1  |                       "range"
formbricks-1  |                     ],
formbricks-1  |                     "message": "Invalid literal value, expected 4"
formbricks-1  |                   }
formbricks-1  |                 ],
formbricks-1  |                 "name": "ZodError"
formbricks-1  |               },
formbricks-1  |               {
formbricks-1  |                 "issues": [
formbricks-1  |                   {
formbricks-1  |                     "code": "invalid_literal",
formbricks-1  |                     "expected": 7,
formbricks-1  |                     "path": [
formbricks-1  |                       "questions",
formbricks-1  |                       6,
formbricks-1  |                       "range"
formbricks-1  |                     ],
formbricks-1  |                     "message": "Invalid literal value, expected 7"
formbricks-1  |                   }
formbricks-1  |                 ],
formbricks-1  |                 "name": "ZodError"
formbricks-1  |               },
formbricks-1  |               {
formbricks-1  |                 "issues": [
formbricks-1  |                   {
formbricks-1  |                     "code": "invalid_literal",
formbricks-1  |                     "expected": 10,
formbricks-1  |                     "path": [
formbricks-1  |                       "questions",
formbricks-1  |                       6,
formbricks-1  |                       "range"
formbricks-1  |                     ],
formbricks-1  |                     "message": "Invalid literal value, expected 10"
formbricks-1  |                   }
formbricks-1  |                 ],
formbricks-1  |                 "name": "ZodError"
formbricks-1  |               }
formbricks-1  |             ],
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "range"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid input"
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "string",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "lowerLabel"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "string",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "upperLabel"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "pictureSelection",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"pictureSelection\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "array",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "choices"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "date",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"date\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "expected": "'M-d-y' | 'd-M-y' | 'y-M-d'",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "format"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "fileUpload",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"fileUpload\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "boolean",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "allowMultipleFiles"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "cal",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"cal\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "string",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "calUserName"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       }
formbricks-1  |     ],
formbricks-1  |     "path": [
formbricks-1  |       "questions",
formbricks-1  |       6
formbricks-1  |     ],
formbricks-1  |     "message": "Invalid input"
formbricks-1  |   }
formbricks-1  | ]
formbricks-1  |     at get error [as error] (/home/nextjs/apps/web/.next/server/chunks/2432.js:1:10493)
formbricks-1  |     at ee.parse (/home/nextjs/apps/web/.next/server/chunks/2432.js:1:12715)
formbricks-1  |     at o (/home/nextjs/apps/web/.next/server/chunks/6011.js:1:11545)
formbricks-1  |     at _ (/home/nextjs/apps/web/.next/server/chunks/6011.js:1:25027)
formbricks-1  |     at /home/nextjs/apps/web/.next/server/app/api/v1/client/[environmentId]/website/sync/route.js:1:2852
formbricks-1  |     at Array.map (<anonymous>)
formbricks-1  |     at y (/home/nextjs/apps/web/.next/server/app/api/v1/client/[environmentId]/website/sync/route.js:1:2837)
formbricks-1  |     at async /home/nextjs/apps/web/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:14:35796
formbricks-1  |     at async eP.execute (/home/nextjs/apps/web/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:14:26839)
formbricks-1  |     at async eP.handle (/home/nextjs/apps/web/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:14:37137) {
formbricks-1  |   issues: [
formbricks-1  |     {
formbricks-1  |       code: 'invalid_union',
formbricks-1  |       unionErrors: [Array],
formbricks-1  |       path: [Array],
formbricks-1  |       message: 'Invalid input'
formbricks-1  |     }
formbricks-1  |   ],
formbricks-1  |   addIssue: [Function (anonymous)],
formbricks-1  |   addIssues: [Function (anonymous)],
formbricks-1  |   errors: [
formbricks-1  |     {
formbricks-1  |       code: 'invalid_union',
formbricks-1  |       unionErrors: [Array],
formbricks-1  |       path: [Array],
formbricks-1  |       message: 'Invalid input'
formbricks-1  |     }
formbricks-1  |   ]
formbricks-1  | }
formbricks-1  | d [ZodError]: [
formbricks-1  |   {
formbricks-1  |     "code": "invalid_union",
formbricks-1  |     "unionErrors": [
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "openText",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"openText\""
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "consent",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"consent\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "string",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "label"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "multipleChoiceSingle",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"multipleChoiceSingle\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "array",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "choices"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "multipleChoiceMulti",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"multipleChoiceMulti\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "array",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "choices"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "nps",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"nps\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "string",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "lowerLabel"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "string",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "upperLabel"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "cta",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"cta\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "boolean",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "buttonExternal"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "rating",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"rating\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "expected": "'number' | 'smiley' | 'star'",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "scale"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_union",
formbricks-1  |             "unionErrors": [
formbricks-1  |               {
formbricks-1  |                 "issues": [
formbricks-1  |                   {
formbricks-1  |                     "code": "invalid_literal",
formbricks-1  |                     "expected": 5,
formbricks-1  |                     "path": [
formbricks-1  |                       "questions",
formbricks-1  |                       6,
formbricks-1  |                       "range"
formbricks-1  |                     ],
formbricks-1  |                     "message": "Invalid literal value, expected 5"
formbricks-1  |                   }
formbricks-1  |                 ],
formbricks-1  |                 "name": "ZodError"
formbricks-1  |               },
formbricks-1  |               {
formbricks-1  |                 "issues": [
formbricks-1  |                   {
formbricks-1  |                     "code": "invalid_literal",
formbricks-1  |                     "expected": 3,
formbricks-1  |                     "path": [
formbricks-1  |                       "questions",
formbricks-1  |                       6,
formbricks-1  |                       "range"
formbricks-1  |                     ],
formbricks-1  |                     "message": "Invalid literal value, expected 3"
formbricks-1  |                   }
formbricks-1  |                 ],
formbricks-1  |                 "name": "ZodError"
formbricks-1  |               },
formbricks-1  |               {
formbricks-1  |                 "issues": [
formbricks-1  |                   {
formbricks-1  |                     "code": "invalid_literal",
formbricks-1  |                     "expected": 4,
formbricks-1  |                     "path": [
formbricks-1  |                       "questions",
formbricks-1  |                       6,
formbricks-1  |                       "range"
formbricks-1  |                     ],
formbricks-1  |                     "message": "Invalid literal value, expected 4"
formbricks-1  |                   }
formbricks-1  |                 ],
formbricks-1  |                 "name": "ZodError"
formbricks-1  |               },
formbricks-1  |               {
formbricks-1  |                 "issues": [
formbricks-1  |                   {
formbricks-1  |                     "code": "invalid_literal",
formbricks-1  |                     "expected": 7,
formbricks-1  |                     "path": [
formbricks-1  |                       "questions",
formbricks-1  |                       6,
formbricks-1  |                       "range"
formbricks-1  |                     ],
formbricks-1  |                     "message": "Invalid literal value, expected 7"
formbricks-1  |                   }
formbricks-1  |                 ],
formbricks-1  |                 "name": "ZodError"
formbricks-1  |               },
formbricks-1  |               {
formbricks-1  |                 "issues": [
formbricks-1  |                   {
formbricks-1  |                     "code": "invalid_literal",
formbricks-1  |                     "expected": 10,
formbricks-1  |                     "path": [
formbricks-1  |                       "questions",
formbricks-1  |                       6,
formbricks-1  |                       "range"
formbricks-1  |                     ],
formbricks-1  |                     "message": "Invalid literal value, expected 10"
formbricks-1  |                   }
formbricks-1  |                 ],
formbricks-1  |                 "name": "ZodError"
formbricks-1  |               }
formbricks-1  |             ],
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "range"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid input"
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "string",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "lowerLabel"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "string",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "upperLabel"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "pictureSelection",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"pictureSelection\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "array",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "choices"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "date",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"date\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "expected": "'M-d-y' | 'd-M-y' | 'y-M-d'",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "format"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "fileUpload",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"fileUpload\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "boolean",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "allowMultipleFiles"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       },
formbricks-1  |       {
formbricks-1  |         "issues": [
formbricks-1  |           {
formbricks-1  |             "received": "address",
formbricks-1  |             "code": "invalid_literal",
formbricks-1  |             "expected": "cal",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "type"
formbricks-1  |             ],
formbricks-1  |             "message": "Invalid literal value, expected \"cal\""
formbricks-1  |           },
formbricks-1  |           {
formbricks-1  |             "code": "invalid_type",
formbricks-1  |             "expected": "string",
formbricks-1  |             "received": "undefined",
formbricks-1  |             "path": [
formbricks-1  |               "questions",
formbricks-1  |               6,
formbricks-1  |               "calUserName"
formbricks-1  |             ],
formbricks-1  |             "message": "Required"
formbricks-1  |           }
formbricks-1  |         ],
formbricks-1  |         "name": "ZodError"
formbricks-1  |       }
formbricks-1  |     ],
formbricks-1  |     "path": [
formbricks-1  |       "questions",
formbricks-1  |       6
formbricks-1  |     ],
formbricks-1  |     "message": "Invalid input"
formbricks-1  |   }
formbricks-1  | ]
formbricks-1  |     at get error [as error] (/home/nextjs/apps/web/.next/server/chunks/2432.js:1:10493)
formbricks-1  |     at ee.parse (/home/nextjs/apps/web/.next/server/chunks/2432.js:1:12715)
formbricks-1  |     at o (/home/nextjs/apps/web/.next/server/chunks/6011.js:1:11545)
formbricks-1  |     at _ (/home/nextjs/apps/web/.next/server/chunks/6011.js:1:25027)
formbricks-1  |     at /home/nextjs/apps/web/.next/server/app/api/v1/client/[environmentId]/website/sync/route.js:1:2852
formbricks-1  |     at Array.map (<anonymous>)
formbricks-1  |     at y (/home/nextjs/apps/web/.next/server/app/api/v1/client/[environmentId]/website/sync/route.js:1:2837)
formbricks-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
formbricks-1  |     at async /home/nextjs/apps/web/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:14:35796
formbricks-1  |     at async eP.execute (/home/nextjs/apps/web/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:14:26839) {
formbricks-1  |   issues: [
formbricks-1  |     {
formbricks-1  |       code: 'invalid_union',
formbricks-1  |       unionErrors: [Array],
formbricks-1  |       path: [Array],
formbricks-1  |       message: 'Invalid input'
formbricks-1  |     }
formbricks-1  |   ],
formbricks-1  |   addIssue: [Function (anonymous)],
formbricks-1  |   addIssues: [Function (anonymous)],
formbricks-1  |   errors: [
formbricks-1  |     {
formbricks-1  |       code: 'invalid_union',
formbricks-1  |       unionErrors: [Array],
formbricks-1  |       path: [Array],
formbricks-1  |       message: 'Invalid input'
formbricks-1  |     }
formbricks-1  |   ]
formbricks-1  | }`

**Comment by mattinannt** [comment]
Fixed with the changes by @andrewnimmo 🚀
